### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by benjick** [alfonsusac/nextjs-better-unstable-cache#5]
Hello!

Wanted to check in on what the recommended usage is for this library and see if I've gotten the correct understanding of it.

This is a small code-snippet:

```tsx
export async function getGroupMembers(groupId: number) {
  const { userAbility } = await createUserAbility();
  if (!userAbility.can("view", subject("Group", { groupId }))) {
    throw new MerlinError("Access denied", "MP9ce");
  }
  const groupMembers = await getGroupMembers_CACHED(groupId);
  return groupMembers;
}

const getGroupMembers_CACHED = memoize(
  async (...props: Parameters<typeof getGroupMembers_UNSAFE>) =>
    await getGroupMembers_UNSAFE(...props),
  {
    persist: true,
    duration: 60,
    revalidateTags: (id) => ["groups", `group=${id}`],
    additionalCacheKey: ["getGroupMembers"],
  },
);

export async function getGroupMembers_UNSAFE(groupId: number) {
  const groupMembers = await db.query.usersToGroups.findMany({
    where: eq(usersToGroups.groupId, groupId),
    with: {
      user: true,
    },
  });
  return groupMembers.map((g) => g.user);
}

export async function joinGroup(formData: FormData) {
  ... stuff
  revalidateTag(`group=${group.id}`);
}
```

Am I right in not caching the outer function? Or should I maybe cache that too so I don't have to retrieve the user session every time (Lucia Auth)?

**Comment by alfonsusac** [comment]
Hi, thanks for checking out this repo. I am in no way an experienced developer but let me give you what my opinion is.

> Am I right in not caching the outer function? Or should I maybe cache that too so I don't have to retrieve the user session every time (Lucia Auth)?
For me, i think this is already a correct approach. You dont need to persist the result of the user authentication since that would not achieve an up-to-date session checking. i.e Your session is already expired but the session-checking function is still cached and that would be undesirable.

What I would like to do is in addition to separating the authentication like that, is also cache the auth()-checking function using `cache()` so that any calls to that auth checks are deduped and you only need to check once PER request.

It totally make sense to check the auth first before going for the cached function, thereby separating the data layer and the auth layer.

**Comment by benjick** [comment]
Thanks for the reply, I appreciate to be able to brainstorm with another dev!

> What I would like to do is in addition to separating the authentication like that, is also cache the auth()-checking function using cache() so that any calls to that auth checks are deduped and you only need to check once PER request.

Thanks for the tip! I checked and the auth framework handles it automatically already, so that's awesome. Thanks for the feedback!

**Comment by benjick** [comment]
Been using this pattern for almost a year now, wanted to share my helper function:

```ts
type MemoizeOptions<T extends unknown[]> = {
  persist: boolean;
  duration: number;
  revalidateTags: (...args: T) => CachePatterns[];
  additionalCacheKey?: string[];
};

const memoizeLogLevels = ["dedupe", "datacache", "verbose"] as const;

export function createCachedFunction<
  TPrepareArgs extends unknown[],
  TReturn,
  TPrepareReturn,
>(
  functions: {
    /**
     * Runs before the function is cached.
     * Can be used to verify permissions, get user data, etc.
     */
    prepare: (...args: TPrepareArgs) => Promise<TPrepareReturn>;
    /**
     * The function to cache.
     *
     * Note: Do *not* use memoize inside here.
     */
    process: (verifyReturn: TPrepareReturn) => Promise<TReturn>;
  },
  /**
   * nextjs-better-unstable-cache options
   */
  memoizeOptions?: MemoizeOptions<[TPrepareReturn]>,
) {
  const maybeCachedFunction = memoizeOptions
    ? memoize(functions.process, {
        ...memoizeOptions,
        log: [...memoizeLogLevels],
      })
    : functions.process;

  const main = async (...args: TPrepareArgs): Promise<TReturn> => {
    const verifyReturn = await functions.prepare(...args);
    return maybeCachedFunction(verifyReturn);
  };

  if (memoizeOptions) {
    main.cached = maybeCachedFunction;
  }
  main.UNSAFE = functions.process;

  return main;
}
```

usage:

```ts
const getUserPosts = createCachedFunction(
  {
    prepare: async (token: string) => {
      if (token.length > 3) throw new Error("Unauthorized");
      return `accepted-${token}`;
    },
    process: async (userId) => {
      const posts = await Promise.resolve(["post1", "post2", userId]);
      return posts;
    },
  },
  {
    persist: true,
    duration: 300,
    revalidateTags: (userId) => [`myGroups=${userId}`],
  },
);
```
