### ISSUE TITLE
PNPM issue:  unmet peer react@next: found 18.2.0

### ISSUE THREAD

**Issue by MaKTaiL** [alfonsusac/nextjs-better-unstable-cache#6]
![image](https://github.com/alfonsusac/nextjs-better-unstable-cache/assets/5403043/3661fa05-6b1e-48a6-aaac-1f844df4d6f4)

I'm getting this warning when installing the package with pnpm. What could it be?

**Comment by alfonsusac** [comment]
It shouldn't be a big deal, I just dont know how to correctly set up the peer dependency to use the react version from Next.js.
